# Generated by Django 5.2.4 on 2025-07-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
