# Generated by Django 5.2.4 on 2025-07-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_applications_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='application_id',
        ),
    ]
