# Generated by Django 5.2.4 on 2025-07-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_remove_applications_application_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
