# Generated by Django 5.2.4 on 2025-08-02 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_applications_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={'ordering': ['-created'], 'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
    ]
