# Generated by Django 5.2.4 on 2025-07-13 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_facilityforgeuser_team_team_manager_and_more'),
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='users',
        ),
        migrations.AddField(
            model_name='facility',
            name='tenants',
            field=models.ManyToManyField(blank=True, null=True, related_name='used_facilities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facility',
            name='engineering_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engineering_facilities', to='accounts.team'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_facilities', to=settings.AUTH_USER_MODEL),
        ),
    ]
