# Generated by Django 5.2.4 on 2025-07-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_remove_facility_users_facility_tenants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
