# Generated by Django 5.2.4 on 2025-07-20 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_team_description_team_moto_team_team_owner_and_more'),
        ('facilities', '0003_facility_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='engineering_team',
        ),
        migrations.AddField(
            model_name='facility',
            name='engineering_teams',
            field=models.ManyToManyField(blank=True, related_name='serviced_facilities', to='accounts.team'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='tenants',
            field=models.ManyToManyField(blank=True, related_name='used_facilities', to=settings.AUTH_USER_MODEL),
        ),
    ]
