# Generated by Django 5.2.4 on 2025-07-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_team_members'),
        ('tickets', '0002_tickets_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tickets',
            field=models.ManyToManyField(blank=True, related_name='teams', to='tickets.tickets'),
        ),
    ]
