# Generated by Django 5.2.4 on 2025-07-22 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_team_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityforgeuser',
            name='rating',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
