# Generated by Django 5.2.4 on 2025-07-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_facilityforgeuser_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityforgeuser',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facilityforgeuser',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
