# Generated by Django 5.2.4 on 2025-08-02 20:34

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketmessages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketmessages',
            options={'ordering': ['created_at'], 'verbose_name': 'Ticket Message', 'verbose_name_plural': 'Ticket Messages'},
        ),
        migrations.AlterModelOptions(
            name='tickets',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.CreateModel(
            name='TicketImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tickets.tickets')),
            ],
        ),
    ]
