# Generated by Django 5.2.4 on 2025-08-03 10:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticketmessages_options_alter_tickets_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='TicketImages',
        ),
    ]
